### ISSUE TITLE
Leftovers of merge conflict in readme

### ISSUE THREAD

**Issue by joris-vercammen-cali** [openfed/AccessibilityCheck#10]
![Screenshot 2019-08-13 at 08 44 36](https://user-images.githubusercontent.com/43645240/62920641-a4495180-bda6-11e9-8456-ec3d16c9f4e8.png)

There seem to be some markers left from a merge that wasn't resolved correctly.

**Comment by stefanruijsenaars** [comment]
Fixed in https://github.com/openfed/AccessibilityCheck/commit/02b923fe8de3affe92b8359c1a18b354264789ae#diff-0a369498a5a8db3ac8fa606b544c9810
