### ISSUE TITLE
Accessibility Checker doesn't take display:none into account

### ISSUE THREAD

**Issue by bdeclerc** [openfed/AccessibilityCheck#11]
On https://accessibility.belgium.be/language_selection_page it gives an error because of an invalid skiplink, but the skiplink has display:none CSS property so is not used/usable - this should not result in an error condition.

**Comment by roelvangils** [comment]
Indeed. The skip link itself is not part of the accessible tree (`display: none` takes it out), so it doesn't point to anything.

HTML CodeSniffer reports:

> This link points to a named anchor "main-content" within the document, but no anchor exists with that name.

aXe/Lighthouse do not report this as an error. Maybe we should file the issue in the [HTML CodeSniffer repository](https://github.com/squizlabs/HTML_CodeSniffer/issues).

**Comment by bdeclerc** [comment]
You're right, I added a ticket #267 on codesniffer.

**Comment by bdeclerc** [comment]
Fixed in Codesniffer
