### ISSUE TITLE
Tool validation gets stucked

### ISSUE THREAD

**Issue by spyrosb4y** [openfed/AccessibilityCheck#6]
**Problem**
Often enough the console runs normally in the background but the ui loader is stucked in a page url  and it doesn't move forward to the next url and it doesn't bring any new results. The page update queue is populated normally but the loader spins infinitely in the same url and the results are not updated.

I am not sure from where this occurs, maybe a moment of internet connection lost ?

**Proposed solution**
I think it would be very helpful to cache the results for each search url input , so we can continue if something like that occurs also to access previous results.

**Comment by bdeclerc** [comment]
Ticket should have been posted on https://github.com/openfed/AccessibilityCheckServer/issues
